### ISSUE TITLE
GATK 3.5 support

### ISSUE THREAD

**Issue by matthdsm** [kaktus42/galaxytools#2]
Hi, 

Great work on integrating a more recent version of GATK in Galaxy!
Do you suppose your wrappers wil work with v3.5?

Thanks
Matthias

**Comment by kaktus42** [comment]
Hi @matthdsm,
the wrapper should also work with the 3.5 version of GATK.
You can give it a try and report back here.

You would have to put the GATK 3.5 jar in the directory of `GATK_PATH` [1].

So far, there are not all tools and parameter options in this tools.
However, there are enough to run a full calling with HC (including BQSR);
also on population size (using CombineGVCFs).

I'm glad, this finds appeal :)
Alexander

[1] https://github.com/kaktus42/galaxytools/blob/master/tools/gatk/tool_dependencies.xml#L4

**Comment by matthdsm** [comment]
Hi Alexander,

Since your last message we've implemented the GATK wrapper on our Galaxy instance, and everything seems to work. I forked this repo and intend to do some more work on it. We're still having some issues getting the tool to talk to our cluster, which is run with Torque instead of Slurm (hence the issue).

So a quick question, what learning resources did you use for the development of the tool? I'm still trying to get the hang of everything, and I feel like the info on the Galaxy wiki doensn't cover everything.

Thanks
Matthias

**Comment by kaktus42** [comment]
Hi @matthdsm,

good to hear, that you could figure out the issues you had.
I'm glad to get some help in the development! Feel free to make a pull request and I can also update the toolshed.

What exactly do you mean with the learning resources? For the BQSR? What organism are you working on?

Best,
Alexander

**Comment by matthdsm** [comment]
I'm working with Hsapiens mostly, but actually I meant to ask where you found all the info on how to create the approriate xml formatting etc. for the tool.

M

**Comment by kaktus42** [comment]
@matthdsm: Then I got your question wrong.
I mainly used the ressources on the wiki [1].
Apart from that I found a lot in the tests of the source code.
And of course, the mailinglist and the IRC channel have been very helpful with a lot of awesome people!

[1] https://wiki.galaxyproject.org/Admin/Tools/AddToolTutorial#Develop.2FResourcesTools.Tool_Development_Resources
